### PR TITLE
Fix a problem with not getting the correct Context on App Engine

### LINKED ISSUE #77: Cannot provide oauth2 with a proper config causing crash on Google App Engine
tl;dr; https://godoc.org/golang.org/x/oauth2#Config.Exchange on Google App Engine needs to get a `context.Context` from `appengine.NewContext(request)`

Longer: I've tried to deploy an app written as stand alone to GAE, worked fine, but when doing a oauth2 with Fb i'm getting an error. It's reproducible on a local GAE playground. The reason is that a GAE provides own http client and http.DefaultClient is blocked.

For now I'm using a hack:
 - a tiny middleware before authboss sets context through gorilla.context
 - a modified version of authboss checks if Context is available

I don't know if it worth fixing, but writing about it to save others time (took me few hours to precisely find the place of error). Maybe  just mention in the documentation.

In general, I think it's worth to consider the Google approach to handlers:
https://godoc.org/golang.org/x/net/context

A solution might be to allow to specify an option (a global in oauth2 subpackage):

```
var ContextProvider func(req *http.Request) context.Context { 
    return oauth2.NoContext
}
```
It would be easier than refactoring all code to provide third argument.

I've tested, second approach is nicer.
notice, one must import `google.golang.org/appengine` instead standard `appengine`

### PR DESCRIPTION
**Pull request by orian**
This fixes #77 

At configuration step, one has to change ContextProvider:
```
ab.ContextProvider = func(r *http.Request) context.Context {
	return appengine.NewContext(r)
}
```

### CODE REVIEW

**Comment by orian** [comment]
This fixes #77

**Comment by bsr203** [comment]
Hi, I too would like to see the support for GAE, and agree Context is a [tiny](https://github.com/golang/net/blob/master/context/context.go) dependency and used widely to support request bound data. it is required to use with GAE. Please consider.

**Comment by aarondl** [comment]
If we can get a rebase, I'd be willing to merge this.

**Comment by buu700** [comment]
This should be good to merge here after @orian merges [orian/authboss/pull/1](https://github.com/orian/authboss/pull/1).

**Comment by aarondl** [comment]
@buu700 I think orian might be inactive to the point where a separate fork would be the quickest way of resolution.

**Comment by buu700** [comment]
Fair enough, just submitted a new PR directly here.

**Comment by aarondl** [comment]
Merged in a rebased PR.

**Pull request closed without merging**
