### PR TITLE
Added required handler for ListenAndServe

### PR DESCRIPTION
**Pull request by golliher**
http.ListenAndServe requires two arguments, the second one can be nil,
but must be present.  https://golang.org/pkg/net/http/#ListenAndServe

Omitting it, even in just documention code snippets like ths one,
might confuse people just learning (like myself).

### CODE REVIEW

**Comment by golliher** [comment]
Hmmm.. I wasn't expecting CircleCI to fail a simple change to the README.     I have no idea how to resolve that.

**Comment by nicolaiskogheim** [comment]
The error is

```
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}

cd /home/ubuntu/.go_project/src/gopkg.in/authboss.v0 && /home/ubuntu/.go_project/bin/goveralls -coverprofile=$CIRCLE_ARTIFACTS/coverage.txt -service=circle-ci -repotoken=$COVERALLS_TOKEN
 returned exit code 1
```

I guess there's a couple of reasons why this could happen, but your edit doesn't have anything to do with it - which I imagine you figured out. The error might go away if the tests gets re-run.


__________________

Anyway, I bet the authors would like you to follow the gofmt style guidelines. Add a space after the comma :)

```go
http.ListenAndServe(":8080", nil)
```

**Comment by aarondl** [comment]
Why do I feel like I've seen this problem with coveralls recently and I fixed it? And yes, do please gofmt any code you pull request first :) I will be responsible for CI and ensuring things pass.

**Comment by golliher** [comment]
I updated my PR to add the space after the comma to comply with gofmt style guidelines.    Thanks for catching that.

**Comment by aarondl** [comment]
I definitely saw this before. All PR's hit this. I've disabled code coverage for PR's and if we were to rebase this it should work now. But we don't need to wait for that. Thanks, LGTM!

**Pull request merged**
